version: '3.7'

services:
  web:
    build: .
    command: sh -c "gunicorn --bind 0.0.0.0:8000 --chdir /star-burger/star-burger/ star_burger.wsgi:application --reload"
    volumes:
      - .:/star-burger/
      - static_volume:/star-burger/star-burger/static
      - media_volume:/star-burger/star-burger/media
    restart: always
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/star-burger/star-burger/static
      - media_volume:/star-burger/star-burger/media
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=starburger_user
      - POSTGRES_PASSWORD=4735833
      - POSTGRES_DB=starburger

volumes:
  postgres_data:
  static_volume:
  media_volume:
