# Generated by Django 3.2 on 2021-08-21 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='адрес')),
                ('lat', models.CharField(blank=True, max_length=100, verbose_name='широта')),
                ('lon', models.CharField(blank=True, max_length=100, verbose_name='долгота')),
                ('update_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
