# Generated by Django 3.2 on 2021-08-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_customerorderdetails_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=400, verbose_name='описание'),
        ),
    ]
