# Generated by Django 3.2 on 2021-08-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя')),
            ],
        ),
    ]
