# Generated by Django 3.2 on 2021-08-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_someclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeClass',
        ),
    ]
