# Generated by Django 3.2 on 2021-08-11 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_orderitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость'),
        ),
    ]
