# Generated by Django 3.2 on 2021-08-11 13:07

from django.db import migrations


def get_order_item_cost(apps, schema_editor):
    OrderItems = apps.get_model('foodcartapp', 'OrderItems')
    for order_item in OrderItems.objects.all().iterator():
        order_item.cost = order_item.price * order_item.quantity
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_orderitems_cost'),
    ]

    operations = [
        migrations.RunPython(get_order_item_cost),
    ]
