# Generated by Django 3.2 on 2021-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_remove_orderitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderdetails',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Обработанный'), ('Unprocessed', 'Необработанный')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
