# Generated by Django 3.2 on 2021-08-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20210813_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderdetails',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарии к заказу'),
        ),
    ]
