# Generated by Django 3.2 on 2021-08-12 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_customerorderdetails_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderdetails',
            name='called_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время звонка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorderdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerorderdetails',
            name='delivered_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время доставки'),
            preserve_default=False,
        ),
    ]
