# Generated by Django 3.2 on 2021-08-12 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20210813_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
    ]
