# Generated by Django 3.2 on 2021-08-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_customerorderdetails_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderdetails',
            name='payment_method',
            field=models.CharField(choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], default='Наличностью', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
