# Generated by Django 3.2 on 2021-08-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_customerorderdetails_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
                ('lat', models.CharField(blank=True, max_length=100, verbose_name='широта')),
                ('lon', models.CharField(blank=True, max_length=100, verbose_name='долгота')),
            ],
        ),
    ]
