# Generated by Django 3.2 on 2021-08-16 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AddField(
            model_name='place',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата обновления'),
        ),
    ]
