# Generated by Django 3.2 on 2021-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20210821_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderdetails',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], default='', max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='customerorderdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('Обработанный', 'Обработанный'), ('Необработанный', 'Необработанный')], default='', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
