# Generated by Django 3.2 on 2021-08-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0063_alter_customerorderdetails_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderdetails',
            name='status',
            field=models.CharField(choices=[('Обработанный', 'Обработанный'), ('Необработанный', 'Необработанный')], default='Необработанный', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
