# Generated by Django 3.2 on 2021-08-21 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0065_alter_customerorderdetails_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderdetails',
            name='address',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customerorderdetails',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время звонка'),
        ),
        migrations.AlterField(
            model_name='customerorderdetails',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='customerorderdetails',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='customerorderdetails',
            name='firstname',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customerorderdetails',
            name='lastname',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customerorderdetails',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], db_index=True, max_length=50, verbose_name='Платежный метод'),
        ),
        migrations.AlterField(
            model_name='customerorderdetails',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.RemoveField(
            model_name='customerorderdetails',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='customerorderdetails',
            name='restaurants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='foodcartapp.restaurant', verbose_name='Рестораны'),
        ),
        migrations.AlterField(
            model_name='customerorderdetails',
            name='status',
            field=models.CharField(choices=[('Обработанный', 'Обработанный'), ('Необработанный', 'Необработанный')], db_index=True, default='Необработанный', max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='update_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата обновления'),
        ),
    ]
