# Generated by Django 3.2 on 2021-08-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0066_auto_20210821_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerOrderDetails',
            new_name='OrderDetails',
        ),
    ]
