# Generated by Django 3.2 on 2021-08-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0068_auto_20210821_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='адрес'),
        ),
    ]
