# Generated by Django 3.2 on 2021-08-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0069_alter_place_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
