# Generated by Django 3.2 on 2021-08-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0071_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='user_order_item',
        ),
    ]
