# Generated by Django 3.2 on 2021-09-09 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0072_rename_user_orderitem_user_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Рестораны'),
        ),
    ]
